language: cpp

os:
    - osx

before_install:
    - brew update
    - brew install qt5 qpm
    - brew link --force qt5 qpm

script:
    - qpm install
    - qmake -config release
    - make
    - macdeployqt "release/OBS Auto Record.app" -dmg
