language: cpp

os:
    - osx

before_install:
    - brew update
    - brew install qt5
    - brew link --force qt5

script:
    - qpm install
    - qmake -config release
    - make
    - macdeployqt "release/OBS Auto Record.app" -dmg
